// utils/states.js

const states = {
    MX: [
      { code: 'AGU', name: 'Aguascalientes' },
      { code: 'BCN', name: 'Baja California' },
      { code: 'BCS', name: 'Baja California Sur' },
      { code: 'CAM', name: 'Campeche' },
      { code: 'CHP', name: 'Chiapas' },
      { code: 'CHH', name: 'Chihuahua' },
      { code: 'CMX', name: 'Ciudad de México' },
      { code: 'COA', name: 'Coahuila' },
      { code: 'COL', name: 'Colima' },
      { code: 'DUR', name: 'Durango' },
      { code: 'GUA', name: 'Guanajuato' },
      { code: 'GRO', name: 'Guerrero' },
      { code: 'HID', name: 'Hidalgo' },
      { code: 'JAL', name: 'Jalisco' },
      { code: 'MEX', name: 'Estado de México' },
      { code: 'MIC', name: 'Michoacán' },
      { code: 'MOR', name: 'Morelos' },
      { code: 'NAY', name: 'Nayarit' },
      { code: 'NLE', name: 'Nuevo León' },
      { code: 'OAX', name: 'Oaxaca' },
      { code: 'PUE', name: 'Puebla' },
      { code: 'QUE', name: 'Querétaro' },
      { code: 'ROO', name: 'Quintana Roo' },
      { code: 'SLP', name: 'San Luis Potosí' },
      { code: 'SIN', name: 'Sinaloa' },
      { code: 'SON', name: 'Sonora' },
      { code: 'TAB', name: 'Tabasco' },
      { code: 'TAM', name: 'Tamaulipas' },
      { code: 'TLA', name: 'Tlaxcala' },
      { code: 'VER', name: 'Veracruz' },
      { code: 'YUC', name: 'Yucatán' },
      { code: 'ZAC', name: 'Zacatecas' }
    ],
    US: [
      { code: 'AL', name: 'Alabama' },
      { code: 'AK', name: 'Alaska' },
      { code: 'AZ', name: 'Arizona' },
      { code: 'AR', name: 'Arkansas' },
      { code: 'CA', name: 'California' },
      { code: 'CO', name: 'Colorado' },
      { code: 'CT', name: 'Connecticut' },
      { code: 'DE', name: 'Delaware' },
      { code: 'FL', name: 'Florida' },
      { code: 'GA', name: 'Georgia' },
      { code: 'HI', name: 'Hawaii' },
      { code: 'ID', name: 'Idaho' },
      { code: 'IL', name: 'Illinois' },
      { code: 'IN', name: 'Indiana' },
      { code: 'IA', name: 'Iowa' },
      { code: 'KS', name: 'Kansas' },
      { code: 'KY', name: 'Kentucky' },
      { code: 'LA', name: 'Louisiana' },
      { code: 'ME', name: 'Maine' },
      { code: 'MD', name: 'Maryland' },
      { code: 'MA', name: 'Massachusetts' },
      { code: 'MI', name: 'Michigan' },
      { code: 'MN', name: 'Minnesota' },
      { code: 'MS', name: 'Mississippi' },
      { code: 'MO', name: 'Missouri' },
      { code: 'MT', name: 'Montana' },
      { code: 'NE', name: 'Nebraska' },
      { code: 'NV', name: 'Nevada' },
      { code: 'NH', name: 'New Hampshire' },
      { code: 'NJ', name: 'New Jersey' },
      { code: 'NM', name: 'New Mexico' },
      { code: 'NY', name: 'New York' },
      { code: 'NC', name: 'North Carolina' },
      { code: 'ND', name: 'North Dakota' },
      { code: 'OH', name: 'Ohio' },
      { code: 'OK', name: 'Oklahoma' },
      { code: 'OR', name: 'Oregon' },
      { code: 'PA', name: 'Pennsylvania' },
      { code: 'RI', name: 'Rhode Island' },
      { code: 'SC', name: 'South Carolina' },
      { code: 'SD', name: 'South Dakota' },
      { code: 'TN', name: 'Tennessee' },
      { code: 'TX', name: 'Texas' },
      { code: 'UT', name: 'Utah' },
      { code: 'VT', name: 'Vermont' },
      { code: 'VA', name: 'Virginia' },
      { code: 'WA', name: 'Washington' },
      { code: 'WV', name: 'West Virginia' },
      { code: 'WI', name: 'Wisconsin' },
      { code: 'WY', name: 'Wyoming' }
    ],
    CA: [
      { code: 'AB', name: 'Alberta' },
      { code: 'BC', name: 'British Columbia' },
      { code: 'MB', name: 'Manitoba' },
      { code: 'NB', name: 'New Brunswick' },
      { code: 'NL', name: 'Newfoundland and Labrador' },
      { code: 'NS', name: 'Nova Scotia' },
      { code: 'NT', name: 'Northwest Territories' },
      { code: 'NU', name: 'Nunavut' },
      { code: 'ON', name: 'Ontario' },
      { code: 'PE', name: 'Prince Edward Island' },
      { code: 'QC', name: 'Quebec' },
      { code: 'SK', name: 'Saskatchewan' },
      { code: 'YT', name: 'Yukon' }
    ],
    ES: [
      { code: 'AN', name: 'Andalucía' },
      { code: 'AR', name: 'Aragón' },
      { code: 'AS', name: 'Asturias' },
      { code: 'CN', name: 'Canarias' },
      { code: 'CB', name: 'Cantabria' },
      { code: 'CM', name: 'Castilla-La Mancha' },
      { code: 'CL', name: 'Castilla y León' },
      { code: 'CT', name: 'Cataluña' },
      { code: 'EX', name: 'Extremadura' },
      { code: 'GA', name: 'Galicia' },
      { code: 'IB', name: 'Islas Baleares' },
      { code: 'RI', name: 'La Rioja' },
      { code: 'MD', name: 'Madrid' },
      { code: 'MC', name: 'Murcia' },
      { code: 'NC', name: 'Navarra' },
      { code: 'PV', name: 'País Vasco' },
      { code: 'VC', name: 'Comunidad Valenciana' }
    ],
    AR: [
      { code: 'BA', name: 'Buenos Aires' },
      { code: 'CA', name: 'Catamarca' },
      { code: 'CH', name: 'Chaco' },
      { code: 'CT', name: 'Chubut' },
      { code: 'CB', name: 'Córdoba' },
      { code: 'CR', name: 'Corrientes' },
      { code: 'ER', name: 'Entre Ríos' },
      { code: 'FO', name: 'Formosa' },
      { code: 'JY', name: 'Jujuy' },
      { code: 'LP', name: 'La Pampa' },
      { code: 'LR', name: 'La Rioja' },
      { code: 'MZ', name: 'Mendoza' },
      { code: 'MN', name: 'Misiones' },
      { code: 'NQ', name: 'Neuquén' },
      { code: 'RN', name: 'Río Negro' },
      { code: 'SA', name: 'Salta' },
      { code: 'SJ', name: 'San Juan' },
      { code: 'SL', name: 'San Luis' },
      { code: 'SC', name: 'Santa Cruz' },
      { code: 'SF', name: 'Santa Fe' },
      { code: 'SE', name: 'Santiago del Estero' },
      { code: 'TF', name: 'Tierra del Fuego' },
      { code: 'TU', name: 'Tucumán' }
    ],
    CO: [
      { code: 'AMA', name: 'Amazonas' },
      { code: 'ANT', name: 'Antioquia' },
      { code: 'ARA', name: 'Arauca' },
      { code: 'ATL', name: 'Atlántico' },
      { code: 'BOL', name: 'Bolívar' },
      { code: 'BOY', name: 'Boyacá' },
      { code: 'CAL', name: 'Caldas' },
      { code: 'CAQ', name: 'Caquetá' },
      { code: 'CAS', name: 'Casanare' },
      { code: 'CAU', name: 'Cauca' },
      { code: 'CES', name: 'Cesar' },
      { code: 'CHO', name: 'Chocó' },
      { code: 'COR', name: 'Córdoba' },
      { code: 'CUN', name: 'Cundinamarca' },
      { code: 'GUA', name: 'Guainía' },
      { code: 'GUV', name: 'Guaviare' },
      { code: 'HUI', name: 'Huila' },
      { code: 'LAG', name: 'La Guajira' },
      { code: 'MAG', name: 'Magdalena' },
      { code: 'MET', name: 'Meta' },
      { code: 'NAR', name: 'Nariño' },
      { code: 'NSA', name: 'Norte de Santander' },
      { code: 'PUT', name: 'Putumayo' },
      { code: 'QUI', name: 'Quindío' },
      { code: 'RIS', name: 'Risaralda' },
      { code: 'SAP', name: 'San Andrés y Providencia' },
      { code: 'SAN', name: 'Santander' },
      { code: 'SUC', name: 'Sucre' },
      { code: 'TOL', name: 'Tolima' },
      { code: 'VAC', name: 'Valle del Cauca' },
      { code: 'VAU', name: 'Vaupés' },
      { code: 'VID', name: 'Vichada' }
    ],
    PE: [
      { code: 'AMA', name: 'Amazonas' },
      { code: 'ANC', name: 'Ancash' },
      { code: 'APU', name: 'Apurímac' },
      { code: 'ARE', name: 'Arequipa' },
      { code: 'AYA', name: 'Ayacucho' },
      { code: 'CAJ', name: 'Cajamarca' },
      { code: 'CAL', name: 'Callao' },
      { code: 'CUS', name: 'Cusco' },
      { code: 'HUV', name: 'Huancavelica' },
      { code: 'HUC', name: 'Huánuco' },
      { code: 'ICA', name: 'Ica' },
      { code: 'JUN', name: 'Junín' },
      { code: 'LAL', name: 'La Libertad' },
      { code: 'LAM', name: 'Lambayeque' },
      { code: 'LIM', name: 'Lima' },
      { code: 'LOR', name: 'Loreto' },
      { code: 'MDD', name: 'Madre de Dios' },
      { code: 'MOQ', name: 'Moquegua' },
      { code: 'PAS', name: 'Pasco' },
      { code: 'PIU', name: 'Piura' },
      { code: 'PUN', name: 'Puno' },
      { code: 'SAM', name: 'San Martín' },
      { code: 'TAC', name: 'Tacna' },
      { code: 'TUM', name: 'Tumbes' },
      { code: 'UCA', name: 'Ucayali' }
    ],
    CL: [
        { code: 'AI', name: 'Aysén' },
        { code: 'AN', name: 'Antofagasta' },
        { code: 'AP', name: 'Arica y Parinacota' },
        { code: 'AR', name: 'La Araucanía' },
        { code: 'AT', name: 'Atacama' },
        { code: 'BI', name: 'Biobío' },
        { code: 'CO', name: 'Coquimbo' },
        { code: 'LI', name: "O'Higgins" },
        { code: 'LL', name: 'Los Lagos' },
        { code: 'LR', name: 'Los Ríos' },
        { code: 'MA', name: 'Magallanes' },
        { code: 'ML', name: 'Maule' },
        { code: 'NB', name: 'Ñuble' },
        { code: 'RM', name: 'Región Metropolitana de Santiago' },
        { code: 'TA', name: 'Tarapacá' },
        { code: 'VS', name: 'Valparaíso' }
      ],
      BR: [
        { code: 'AC', name: 'Acre' },
        { code: 'AL', name: 'Alagoas' },
        { code: 'AM', name: 'Amazonas' },
        { code: 'AP', name: 'Amapá' },
        { code: 'BA', name: 'Bahia' },
        { code: 'CE', name: 'Ceará' },
        { code: 'DF', name: 'Distrito Federal' },
        { code: 'ES', name: 'Espírito Santo' },
        { code: 'GO', name: 'Goiás' },
        { code: 'MA', name: 'Maranhão' },
        { code: 'MG', name: 'Minas Gerais' },
        { code: 'MS', name: 'Mato Grosso do Sul' },
        { code: 'MT', name: 'Mato Grosso' },
        { code: 'PA', name: 'Pará' },
        { code: 'PB', name: 'Paraíba' },
        { code: 'PE', name: 'Pernambuco' },
        { code: 'PI', name: 'Piauí' },
        { code: 'PR', name: 'Paraná' },
        { code: 'RJ', name: 'Río de Janeiro' },
        { code: 'RN', name: 'Río Grande del Norte' },
        { code: 'RO', name: 'Rondônia' },
        { code: 'RR', name: 'Roraima' },
        { code: 'RS', name: 'Río Grande del Sur' },
        { code: 'SC', name: 'Santa Catarina' },
        { code: 'SE', name: 'Sergipe' },
        { code: 'SP', name: 'São Paulo' },
        { code: 'TO', name: 'Tocantins' }
      ]
};
export default states;
    